stages:  
  - build  
  - deploy

build_dev:  
  image: node:latest
  stage: build  
  only:
    - dev
  environment:
    name: dev
  variables:
    APP_NAME: '"Seeds Simulation Dev"'
    NETWORK_BLOCKCHAIN: '"eos"'
    NETWORK_CHAIN_ID: '"1eaa0824707c8c16bd25145493bf062aecddfeb56c736f6ba6397f3195f33c9f"'
    NETWORK_HOST: '"testnet.eos.miami"'
    NETWORK_PORT: '443'
    NETWORK_PROTOCOL: '"https"'
    WEBSERVICES_URL: '"https://fqbkgjgig0.execute-api.eu-west-1.amazonaws.com/dev"'
    WEBSERVICES_API_KEY: '"Zo3L4h85H4TxltCRRrJR70SIfVSWQJW15MbwsTzg"'
    BASE_REPOSITORY_URL: '"https://seeds-simulations-dev.s3-eu-west-1.amazonaws.com"'
    RETRY_DELAY: '5000'
    WAKE_DB_TIME: '15'
  cache:
    paths:
      - node_modules/
  script:    
     # Install vuecli    
    - yarn global add @quasar/cli
    # Install dependencies
    - yarn install
    # Deploy chain manifests config file based on env
    - mv src/statics/chain-manifests-dev.json src/statics/chain-manifests.json 
    # Build App    
    - yarn build  
  artifacts:    
    paths:      
      # Build folder      
      - dist/    
    expire_in: 1 hour

build_prod:  
  image: node:latest
  stage: build  
  only:
    - master
  environment:
    name: production
  variables:
    APP_NAME: '"Seeds Simulation"'
    NETWORK_BLOCKCHAIN: '"eos"'
    NETWORK_CHAIN_ID: '"4667b205c6838ef70ff7988f6e8257e8be0e1284a2f59699054a018f743b1d11"'
    NETWORK_HOST: '"telos.caleos.io"'
    NETWORK_PORT: '443'
    NETWORK_PROTOCOL: '"https"'
    WEBSERVICES_URL: '"https://fqbkgjgig0.execute-api.eu-west-1.amazonaws.com/dev"'
    WEBSERVICES_API_KEY: '"Zo3L4h85H4TxltCRRrJR70SIfVSWQJW15MbwsTzg"'
    BASE_REPOSITORY_URL: '"https://seeds-simulations-dev.s3-eu-west-1.amazonaws.com"'
    RETRY_DELAY: '5000'
    WAKE_DB_TIME: '15'
  cache:
    paths:
      - node_modules/
  script:    
    # Install vuecli    
    - yarn global add @quasar/cli    
    # Install dependencies    
    - yarn install
    # Deploy chain manifests config file based on env
    - mv src/statics/chain-manifests-prod.json src/statics/chain-manifests.json
    # Build App    
    - yarn build  
  artifacts:    
    paths:      
      # Build folder      
      - dist/    
    expire_in: 1 hour

  
deploy_dev:  
  image: python:latest  
  stage: deploy  
  only:    
    - dev
  environment:
    name: dev
  script:    
    - echo $CI_ENVIRONMENT_NAME
    - pip install awscli    
    - aws configure set aws_access_key_id $AWS_KEY
    - aws configure set aws_secret_access_key $AWS_SECRET
    - aws s3 rm s3://seeds-simulation-dev
    - aws s3 sync ./dist/spa s3://seeds-simulation-dev
    - aws cloudfront create-invalidation --distribution-id $AWS_DIST_ID --paths "/*"

deploy_prod:  
  image: python:latest  
  stage: deploy  
  only:    
    - master  
  environment:
    name: production
  script:    
    - echo $CI_ENVIRONMENT_NAME
    - pip install awscli    
    - aws configure set aws_access_key_id $AWS_KEY
    - aws configure set aws_secret_access_key $AWS_SECRET
    - aws s3 rm s3://seeds-simulation-prod
    - aws s3 sync ./dist/spa s3://seeds-simulation-prod
    - aws cloudfront create-invalidation --distribution-id $AWS_DIST_ID --paths "/*"